ENV["VAGRANT_DEFAULT_PROVIDER"] ||= "qemu"

Vagrant.configure("2") do |config|
  config.vm.box = "perk/ubuntu-2204-arm64"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.provider "qemu" do |qemu|
    qemu.memory = "1G"
    qemu.smp = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y --no-install-recommends build-essential
  SHELL
end